/*
==============================================================================

ToolBlox utility functions

Miscellaneous utility functions that make modding more accessible.

==============================================================================
*/



/*
----------------------------------------------------------
Do nothing

Empty function to use when an event should not be handled.
----------------------------------------------------------
*/
void() tbx_DoNothing = {};