/*
==============================================================================

Quake variables

Pre-emptive variable definitions for global referencing.

==============================================================================
*/



/*
==========
Quake Core
==========
*/

/*
-------------
quake_core.qc
-------------
*/
float quake_tick;
float quake_second;

/*
---------------
quake_entity.qc
---------------
*/
.vector quake_oldVelocity;
.vector quake_soakTypes;
.float quake_flags;